### ISSUE TITLE
BENCHMARK_TEMPLATE causes Full Benchmark to Fail

### ISSUE THREAD

**Issue by eyepatchParrot** [FredTingaud/quick-bench-front-end#1]
Running a full benchmark on a template using BENCHMARK_TEMPLATE causes perf to fail with the following message:

> Error or timeout
> {
>   "context": {
>     "date": "2017-07-09 01:48:24",
>     "num_cpus": 1,
>     "mhz_per_cpu": 2400,
>     "cpu_scaling_enabled": false,
>     "library_build_type": "release"
>   },
>   "benchmarks": [
>     {
>       "name": "BM_Fn",
>       "iterations": 270813972,
>       "real_time": 10,
>       "cpu_time": 3,
>       "time_unit": "ns"
>     },
>     {
>       "name": "Noop",
>       "iterations": 272494899,
>       "real_time": 11,
>       "cpu_time": 3,
>       "time_unit": "ns"
>     }
>   ]
> }
> [ perf record: Woken up 2 times to write data ]
> [nfs] with build id 174d45f353bce153f3516aef8bddb712f9752709 not found, continuing without symbols
> [ perf record: Captured and wrote 0.487 MB perf.data (7897 samples) ]
> chmod: cannot access 'command': No such file or directory

```
void f() {}

using Fn = void();
template<Fn* g>
static void BM_Fn(benchmark::State& state) {
  while (state.KeepRunning())
    g();
}

BENCHMARK_TEMPLATE(BM_Fn, f);
```

**Comment by FredTingaud** [comment]
It seems to have been solved at some point in the past.
