### ISSUE TITLE
Results view scaling and scrolling issues

### ISSUE THREAD

**Issue by easyaspi314** [FredTingaud/quick-bench-front-end#10]
macOS 10.13.6 shoehorned onto the MacBook (13-inch, Mid 2009) sporting a "glorious" 13.3" 1280x800 LCD display.
Firefox 63.0.1
Safari 12.0.1

As you can see in the screenshot (from Firefox), the assembly view fails to resize properly, and the body scrolls. I presume that it has something to do with the Monaco scroll bar.
![screen shot 2018-11-17 at 4 54 34 pm](https://user-images.githubusercontent.com/6258309/48666128-82c27000-ea89-11e8-9746-07748ebf1e7f.png)

Safari displays it "properly", but it has some ratio issues. 
![screen shot 2018-11-17 at 5 05 33 pm](https://user-images.githubusercontent.com/6258309/48666196-0df03580-ea8b-11e8-9ffe-08924cc07ecb.png)
How is anyone going to read that?

**Comment by FredTingaud** [comment]
There is indeed a problem with the Firefox view. I need to work on it.
For the ratio issue, you can press on the icon with two arrows on the right of the ASM view, to have it take the full height.
