### ISSUE TITLE
Quick Bench Local setup

### ISSUE THREAD

**Issue by saatvikshah1994** [FredTingaud/quick-bench-front-end#11]
Hi, I came across this [reddit post](https://www.reddit.com/r/cpp/comments/6hkkxu/quickbenchcom_simple_online_c_performance/) about QuickBench where it is mentioned that there is a deploy script to setup quick bench up locally. Where could this or any other installation instructions be found?

I searched the codebase on github but couldnt find it.

**Comment by FredTingaud** [comment]
Hi!
You will also need the other repository: https://github.com/FredTingaud/quick-bench-back-end
It's in this other one that the deploy script is. But it needs some work to work correctly locally. I need to work on that soon!

**Comment by FredTingaud** [comment]
You can now use https://github.com/FredTingaud/bench-runner to run Quick Bench and Build Bench locally.
