### ISSUE TITLE
assembly editor is not visible in safari

### ISSUE THREAD

**Issue by dab0bby** [FredTingaud/quick-bench-front-end#2]
The assembly editor is not visible except the tabs

<img width="1414" alt="screen shot 2017-07-28 at 18 07 51" src="https://user-images.githubusercontent.com/9976654/28726058-e6c36e52-73bf-11e7-9f32-6940e0ce1a63.png">

On Chrome it works fine

**Comment by FredTingaud** [comment]
Thanks for reporting it. It is indeed a problem I am aware of, but I don't have a Safari environment to test fixes, so I am reduced to trying blind fixes.
If by chance somebody has a fix, I would be very interested.

**Comment by gpsbabel** [comment]
I just brought up http://quick-bench.com/tinSGtygCMJuvYxhiDq40IitKew in Safari 12.0.3 with intent to debug/patch it. I was unable to distinguish the difference in the machine source and definitely see the appropriate text in the assembly view frame. (Safari's WebView is slightly different than Chrome's and stopping on JavaScript errors can be a bit surprising.)

I'd say that @FredTingaud 's change was effective. He should be thanked and this problem closed, IMO.

Cheers!
<img width="995" alt="screen shot 2019-02-02 at 10 02 09 pm" src="https://user-images.githubusercontent.com/12013583/52172533-dcf0da00-2736-11e9-806d-e9718cab6a36.png">

**Comment by FredTingaud** [comment]
Issue fixed
