### ISSUE TITLE
Support setting the x86 disassembler style 

### ISSUE THREAD

**Issue by MattPD** [FredTingaud/quick-bench-front-end#23]
Essentially: Expose the UI support for the following feature in `perf`: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f69b64f73e1d7f47a9205c1cd46e0e1c3c65e1cd

The underlying support exists in `objdump` (which is used by `perf` itself): https://lkml.org/lkml/2011/9/29/482

For example, `perf report -M intel` selects the Intel syntax (instead of the default AT&T syntax).

**Comment by hawkinsw** [comment]
@FredTingaud I am working on this as we speak! I hope to have a patch for it by the end of the weekend!

**Comment by FredTingaud** [comment]
Nice!
It's a pretty complex dev as it will require to change the whole chain, from the front-end to the containers. Don't hesitate to post if you are stuck and improving the documentation could help.

**Comment by hawkinsw** [comment]
I am just doing some testing now. I think that I got it working!

**Comment by lhmouse** [comment]
And Intel syntax shall be the default. That's the only standard and documented syntax.

**Comment by MattPD** [comment]
Closing, as setting the format seems to work (already fixed by #63 and related changes in the backend & docker projects).
The default may be a good idea, too, although that may warrant a distinct, new issue.

**Comment by lhmouse** [comment]
> Closing, as setting the format seems to work (already fixed by #63 and related changes in the backend & docker projects). The default may be a good idea, too, although that may warrant a distinct, new issue.

I have opened #84 for that.
