### ISSUE TITLE
No results if "Record disassembly" is not selected.

### ISSUE THREAD

**Issue by cassioneri** [FredTingaud/quick-bench-front-end#37]
Steps to reproduce follow. In a fresh section (the one with StringCreation and StringCopy)

1. Uncheck "Record disassembly" ;
2. Push "Run Benchmark".

The above will state "Showing cached results" but no result/chart is shown. Then,

3. Check "Clear cached results";
4. Push "Run Benchmark".

The progress bar appears and starts growing. However, after a few seconds it stops and no result is shown.

Workaround:

5. Check "Record disassembly" ;
6. Check "Clear cached results";
7. Push "Run Benchmark".

Results are shown after a few seconds.

**Comment by FredTingaud** [comment]
Thanks for the step by step!
