### ISSUE TITLE
Gcc is killed

### ISSUE THREAD

**Issue by marbub** [FredTingaud/quick-bench-front-end#4]
I get the error log:
Error or timeout
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See  for instructions.

Maybe it is to complicated and takes to long.

http://quick-bench.com/Go_6JmTV2S9mMJrQ7b6DPiU1PCY#

**Comment by FredTingaud** [comment]
Thanks for the report.
The permalink is generated only if the benchmark works, so the link you gave me is for a case where it works.
Could you please copy-paste here the code that breaks gcc?

Thanks

**Comment by marbub** [comment]
[benchmark-example.txt](https://github.com/FredTingaud/quick-bench-front-end/files/1471359/benchmark-example.txt)

**Comment by FredTingaud** [comment]
The error is probably due to the fact that there is not enough memory to compile your code.
I increased the memory by container, so it might work now.
