### ISSUE TITLE
Minor cosmetic issue - benchmarked function highlighting

### ISSUE THREAD

**Issue by valiko-ua** [FredTingaud/quick-bench-front-end#40]
If function name is substring of "BENCHMARK", it is highlighted in a wrong place.

- Example 1:

![quickbench-highlight](https://user-images.githubusercontent.com/13869060/95196246-7ca21d80-07e0-11eb-8e76-e770b9cb6cec.png)

- [Example 2](https://quick-bench.com/q/BIgy8RRz7WUb-XNpMcomlSUK8Gk)

**Comment by valiko-ua** [comment]
Note also the left color bar, it looks incorrect.

**Comment by FredTingaud** [comment]
It should work now.
