### ISSUE TITLE
Enable -fcoroutines compiler feature for Gcc 10 or add Gcc 11?

### ISSUE THREAD

**Issue by ghost** [FredTingaud/quick-bench-front-end#53]
For Gcc 10 coroutines is enabled via command line option -fcoroutines and would be nice to have turned on.

Alternative/and would be adding Gcc 11 compiler which has the feature enabled by default.

Note: I do not know what the status of c++20 coroutines is for clang compilers.

**Comment by FredTingaud** [comment]
This works now, using the "Other flags" button.
