### ISSUE TITLE
quick-bench keeps random result of benchmark

### ISSUE THREAD

**Issue by aureliano15** [FredTingaud/quick-bench-front-end#8]
5 different tests, where 37-th string of source file "const auto& v = x[i];" has different indents:

http://quick-bench.com/8tXM_DBFh3F4wSnl-zy8sjHnKDE
http://quick-bench.com/mBRcAF79cbG76pI5QGUo2BHtMtw
http://quick-bench.com/hb3xATTRdzF3hjRwY9ywGPzjC5A
http://quick-bench.com/8DkPXk_iyy6QsSBCjTGoEmc4jGw
http://quick-bench.com/Ss-YGFhfuQvnj2gVgrCqBS8pYQY

1-st test very bad, others good.

Random result of test forever keeps on the server.

**Comment by aureliano15** [comment]
Understanded. It was necessary to enable checkbox "Clear cached results".

**Comment by FredTingaud** [comment]
Indeed, it is possible to clear these data by using "Clear cached results".
